# Generated by Django 2.2.28 on 2022-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressdptfybmfxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdptfybmfxo',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
