# Generated by Django 2.2.28 on 2022-11-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_addressdptfybmfxo_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdptfybmfxo',
            name='sdfgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
